In [21]:
import numpy as np

In [22]:
import pandas as pd

In [23]:
from matplotlib import pyplot as plt

In [24]:
data1=pd.read_csv("Odisha_Data.csv")

In [25]:
data2= pd.read_csv("2024_Literacy_Odisha_data.csv")

In [26]:
data1

,District,Headquarters,Population (2011),Males,Females,Percentage decadal growth 2001–2011,Sex ratio,Density (persons per km2),Child population 0–6 years,Child sex ratio,Literacy rate
0,Anugul,Anugul,"1,271,703","654,898","616,805",11.55,942,199,"145,690",884,78.96
1,Balangir,Balangir,"1,648,574","831,349","817,225",23.29,983,251,"206,964",951,65.50
2,Balasore,Baleswar,"2,317,419","1,184,371","1,133,048",14.47,957,609,"274,432",941,80.66
3,Bargarh,Bargarh,"1,478,833","748,332","730,501",9.84,976,253,"156,185",946,75.16
4,Bhadrak,Bhadrak,"1,506,522","760,591","745,931",12.95,981,601,"176,793",931,83.25
5,Baudh,Baudh,"439,917","220,993","218,924",17.82,991,142,"59,094",975,72.51
6,Cuttack,Cuttack,"2,618,708","1,339,153","1,279,555",11.87,955,666,"251,152",913,84.20
7,Debagarh,Debagarh,"312,164","158,017","154,147",13.88,976,106,"38,621",917,73.07
8,Dhenkanal,Dhenkanal,"1,192,948","612,597","580,351",11.82,947,268,"132,647",870,79.41
9,Gajapati,Paralakhemundi,"575,880","282,041","293,839",10.99,"1,042",133,"82,777",964,54.29
10,Ganjam,Chhatrapur,"3,520,151","1,777,324","1,742,827",11.37,981,429,"397,920",899,71.88
11,Jagatsinghapur,Jagatsinghapur,"1,136,604","577,699","558,905",7.44,967,681,"103,517",929,87.13
12,Jajpur,Jajpur,"1,826,275","926,058","900,217",12.43,972,630,"207,310",921,80.44
13,Jharsuguda,Jharsuguda,"579,499","297,014","282,485",12.56,951,274,"61,823",938,78.36
14,Kalahandi,Bhawanipatna,"1,573,054","785,179","787,875",17.79,"1,003",199,"214,111",947,60.22
15,Kandhamal,Phulbani,"731,952","359,401","372,551",12.92,"1,037",91,"106,379",960,65.12
16,Kendrapara,Kendrapara,"1,439,891","717,695","722,196",10.59,"1,006",545,"153,443",921,85.93
17,Kendujhar,Kendujhar,"1,802,777","907,135","895,642",15.42,987,217,"253,418",957,69.00
18,Khordha,Khordha,"2,246,341","1,166,949","1,079,392",19.65,925,799,"222,275",910,87.51
19,Koraput,Koraput,"1,376,934","677,864","699,070",16.63,"1,031",156,"215,518",970,49.87
20,Malkangiri,Malkangiri,"612,727","303,913","308,814",21.53,"1,016",106,"105,636",979,49.49
21,Mayurbhanj,Baripada,"2,513,895","1,253,633","1,260,262",13.06,"1,005",241,"337,757",952,63.98
22,Nabarangapur,Nabarangpur,"1,218,762","604,046","614,716",18.81,"1,018",230,"201,901",988,48.20
23,Nayagarh,Nayagarh,"962,215","502,194","460,021",11.30,916,247,"101,337",851,79.17
24,Nuapada,Nuapada,"606,490","300,307","306,183",14.28,"1,020",157,"84,893",971,58.20
25,Puri,Puri,"1,697,983","865,209","832,774",13.00,963,488,"164,388",924,85.37
26,Rayagada,Rayagada,"961,959","469,672","492,287",15.74,"1,048",136,"141,167",955,50.88
27,Sambalpur,Sambalpur,"1,044,410","529,424","514,986",12.24,973,158,"112,946",931,76.91
28,Subarnapur,Sonepur,"652,107","332,897","319,210",20.35,959,279,"76,536",947,74.42
29,Sundargarh,Sundargarh,"2,080,664","1,055,723","1,024,941",13.66,971,214,"249,020",937,74.13

In [27]:
data2

          District Population(2024)  Literacy rate
0          Khordha        22,51,673          86.88
1   Jagatsinghapur        11,36,971          86.59
2          Cuttack        26,24,470          85.50
3       Kendrapara        14,40,361          85.15
4             Puri        16,98,730          84.67
5          Bhadrak        15,06,337          82.87
6         Nayagarh         9,62,789          80.42
7           Jajpur        18,27,192          80.13
8         Balasore        23,20,529          79.79
9       Jharsuguda         5,79,505          78.86
10       Dhenkanal        11,92,811          78.76
11          Anugul        12,73,821          77.53
12         Bargarh        14,81,255          74.62
13      Subarnapur         6,10,187          74.42
14      Sundargarh        20,93,437          73.34
15        Debagarh         3,12,520          72.57
16           Baudh        44,11,162          71.61
17          Ganjam        35,29,031          71.09
18       Kendujhar        18,01,733          68.24
19        Balangir        16,48,997          64.72
20       Kandhamal         7,33,110          64.13
21      Mayurbhanj        25,19,738          63.17
22       Kalahandi        15,76,869          59.22
23         Nuapada         6,10,382          57.35
24        Gajapati         5,77,817          53.49
25        Rayagada         9,67,911          49.76
26         Koraput        13,79,647          49.21
27      Malkangiri         6,13,192          48.54
28    Nabarangapur        12,20,946          46.43
29       Sambalpur        10,41,099          76.22

In [31]:
dataset_2021=data1.loc[:,['District','Population (2011)','Literacy rate']]
dataset_2021

          District Population (2011)  Literacy rate
0           Anugul         1,271,703          78.96
1         Balangir         1,648,574          65.50
2         Balasore         2,317,419          80.66
3          Bargarh         1,478,833          75.16
4          Bhadrak         1,506,522          83.25
5            Baudh           439,917          72.51
6          Cuttack         2,618,708          84.20
7         Debagarh           312,164          73.07
8        Dhenkanal         1,192,948          79.41
9         Gajapati           575,880          54.29
10          Ganjam         3,520,151          71.88
11  Jagatsinghapur         1,136,604          87.13
12          Jajpur         1,826,275          80.44
13      Jharsuguda           579,499          78.36
14       Kalahandi         1,573,054          60.22
15       Kandhamal           731,952          65.12
16      Kendrapara         1,439,891          85.93
17       Kendujhar         1,802,777          69.00
18         Khordha         2,246,341          87.51
19         Koraput         1,376,934          49.87
20      Malkangiri           612,727          49.49
21      Mayurbhanj         2,513,895          63.98
22    Nabarangapur         1,218,762          48.20
23        Nayagarh           962,215          79.17
24         Nuapada           606,490          58.20
25            Puri         1,697,983          85.37
26        Rayagada           961,959          50.88
27       Sambalpur         1,044,410          76.91
28      Subarnapur           652,107          74.42
29      Sundargarh         2,080,664          74.13

In [35]:
dataset_2024=data2.loc[:,['District','Population(2024)','Literacy rate']]
dataset_2024

          District Population(2024)  Literacy rate
0          Khordha        22,51,673          86.88
1   Jagatsinghapur        11,36,971          86.59
2          Cuttack        26,24,470          85.50
3       Kendrapara        14,40,361          85.15
4             Puri        16,98,730          84.67
5          Bhadrak        15,06,337          82.87
6         Nayagarh         9,62,789          80.42
7           Jajpur        18,27,192          80.13
8         Balasore        23,20,529          79.79
9       Jharsuguda         5,79,505          78.86
10       Dhenkanal        11,92,811          78.76
11          Anugul        12,73,821          77.53
12         Bargarh        14,81,255          74.62
13      Subarnapur         6,10,187          74.42
14      Sundargarh        20,93,437          73.34
15        Debagarh         3,12,520          72.57
16           Baudh        44,11,162          71.61
17          Ganjam        35,29,031          71.09
18       Kendujhar        18,01,733          68.24
19        Balangir        16,48,997          64.72
20       Kandhamal         7,33,110          64.13
21      Mayurbhanj        25,19,738          63.17
22       Kalahandi        15,76,869          59.22
23         Nuapada         6,10,382          57.35
24        Gajapati         5,77,817          53.49
25        Rayagada         9,67,911          49.76
26         Koraput        13,79,647          49.21
27      Malkangiri         6,13,192          48.54
28    Nabarangapur        12,20,946          46.43
29       Sambalpur        10,41,099          76.22